var AppConstants = {
	CREATE: "CREATE",
	DESTROY: "DESTROY",
	UPDATE_FIELD_NAME: "UPDATE_FIELD_NAME",
	UPDATE_FIELD_TYPE: "UPDATE_FIELD_TYPE",
	UPDATE_TABLE_ID: "UPDATE_TABLE_ID"
}

export default AppConstants